# Generated by Django 4.0.5 on 2022-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(max_length=200)),
                ('services_duration', models.IntegerField()),
                ('services_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
